export const lightTheme = {
    background: '#ffffff',
    text: '#000000',
    inputBackground: '#ffffff',
    inputText: '#333333',
    inputPlaceholder: '#6a6a6a',
    tableHeader: '#000000',
    tableHeaderText: '#ffffff',
    tableRowOdd: '#ffffff',
    tableRowEven: '#f5f5f5',
    tableHover: '#dcdcdc',
    buttonTextDef: '#0042ff',
    buttonTextRed: '#ff0000',
    buttonTextOrange: '#ff6000',
    buttonBg: '#f0f0f0',
    activeTabBorder: 'blue',
};

export const darkTheme = {
    background: '#121212',
    text: '#ffffff',
    inputBackground: '#1e1e1e',
    inputText: '#ffffff',
    inputPlaceholder: '#aaaaaa',
    tableHeader: '#333333',
    tableHeaderText: '#ffffff',
    tableRowOdd: '#1e1e1e',
    tableRowEven: '#2a2a2a',
    tableHover: '#3a3a3a',
    buttonTextDef: '#34b800',
    buttonTextRed: '#aa0000',
    buttonTextOrange: '#aa4001',
    buttonBg: '#333333',
    activeTabBorder: '#66aaff',
};
